### PR TITLE
Fixing the assignment of the embedded manifold (hle).

### PR DESCRIPTION
**Pull request by rymc**
Previously hle was being set to the autoencoder hidden layer, rather than the UMAP manifold.
The only impact of this was in terms of visualization, as the objects reference to hle was only used for visualization - for clustering the local (correct) hle reference was used.

### CODE REVIEW

**Comment by josephsdavid** [comment]
Makes sense, merging!

**Comment by rymc** [comment]
Thanks for merging. It may be a good idea to update the README with the new visualizations too! 

Edit: I see that the images come directly from the repo and there is no need to update the README. My bad.

**Comment by josephsdavid** [comment]
Will do! Currently updating tensorflow which has turned into rebuilding it, so ill fix it when that is finished, and get the proper code on Pypi :)

**Comment by josephsdavid** [comment]
Actually ill rebuild in the morning this is much more enjoyable

**Comment by rymc** [comment]
I'm not sure what happened but it looks like this commit [1] brought in the old incorrect visualisations rather than the visualisations from this pull request.

[1] https://github.com/josephsdavid/N2D-OOP/commit/6205cd71db9f023f1f359218ab91b569c67b5793

**Comment by josephsdavid** [comment]
yep, just noticed my stupid mistake

**Comment by josephsdavid** [comment]
Oh man yeah this is worlds better!

**Pull request merged**
